### ISSUE TITLE
EPIC: reimplementation Core enrichment functions

### ISSUE THREAD

**Issue by ZhimingYe** [ZhimingYe/EnrichGT#40]
- [x] reimplementation of ORA function
- [x] reimplementation of GSEA function
- [x] Test ORA single function
- [ ] Test ORA multi function
- [x] Warp fGSEA fun
- [x] Test GSEA function
- [x] Fix Build up Ranked gs function
- [x] Fix Infer Act
- [x] Export get DB
- [x] Clean up Docs

**Comment by ZhimingYe** [comment]
complete
